config/routes.rb
Planner::Application.routes.draw do

	devise_for :users

	#root to: "devise/sessions#new", as: "user_root"

	devise_scope :user do
		authenticated :user do
			root 'events#index', as: :authenticated_root
		end

		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end


	#resources :events
	resources :users

	#get '/events/:id/gcreate', to: 'events#gcreate', as: "gevent" #google calendar attempt

	resources :events do
	  collection do
	    get :search #get '/events/search/', to: 'events#search', as: "search"
	    get :show_private
	    get :show_deleted
	  end
	end

	get '/events/:id/restore', to: 'events#restore', as: "restore"

end

app/models/event.rb
class Event < ActiveRecord::Base

	validates :title, :event_date, :begti, {presence: true}
	#validates :begti, presence: {message: "Begin time can't be blank"}

	validate :endti, if: :event_has_length
	#validate end time only makes sense if the event has a specific length


	def event_has_length
	#blank checkbox = false

		puts "begti = '#{begti}'"

		if !begti.nil?
			puts "not empty"
		else puts "empty"
		end

		if self.has_length 
			#puts "validating #{endti} to see if it goes after #{begti}"
			puts "validating #{endti}"

			#if !begti.nil?
				validates_time :endti, after: :begti, after_message: "must be after start time"
			#else
				#false	
			#end

		else
			true
		end
	end




	def after_error_message
		return "End time must be after start time"
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  		 :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :authenticate_user!

	def index
<<<<<<< HEAD

		#send email of last sign in
		PlannieNotifier.last_sign_in.deliver

		@events = Event.where(email: current_user.email, deleted: false, is_private: false).order(:event_date)
=======
		@events = Event.where(email: current_user.email, deleted: false, is_private: false).order(:event_date, :begti, :endti)
>>>>>>> fafdef139eb85c7f89e8ac08c15cd3e7e9e8a2e3

		if !@events.empty?
			@current_day = @events[0].event_date
		end
		@to_display  = "I"
	end


	def show #show a particular event
		@event = Event.find(params[:id])

		#The 'export' to Google calendar needs the date in the following format:
		#START/END where START and END are in ISO8601 format:
		#example = 20140127T224000Z/20140320T221500Z

		iso_date  = @event.event_date.strftime("%Y%m%d")

		iso_begti = @event.begti.strftime("%H%M%S")
		iso_endti = @event.endti.strftime("%H%M%S")

		@complete_date = "#{iso_date}T#{iso_begti}Z/#{iso_date}T#{iso_endti}Z"
	end


	def new
		@event = Event.new
	end


	def create
		if params[:commit] != "Create"
			redirect_to events_path
		else
			@event = Event.new(safe_params)

			@event.email   = current_user.email
			@event.deleted = false

			#if the event has no length, we set endtime=starttime before saving to avoid errors:
			if !params[:has_length]
				@event.endti   = @event.begti
			end

			if @event.save
				redirect_to events_path
			else
				render :new
			end
		end
	end



	def edit
		@event = Event.find(params[:id])
	end


	def update
		@event = Event.find(params[:id])

		if params[:commit] == "Cancel"
			redirect_to @event
		else
			if @event.update(safe_params)
				redirect_to @event
			else
				render :edit
			end				
		end

	end


	def destroy
		@event = Event.find(params[:id])
		@event.deleted = true
		if @event.save
			redirect_to events_path
		else
			#there was a problem deleting the record
		end
	end



	def search
		#This search method does not search for deleted events
		#It is also case sensitive

		@events = []

		if !params[:search_this].empty?

			#search events by title and comments (using OR)
			#The 'where' query returns an ActiveRecord::Relation
			@events = Event.where(["email = ? and deleted = ? and (title LIKE ? or comments LIKE ?)", "#{current_user.email}", false, "%#{params[:search_this]}%", "%#{params[:search_this]}%"]).order(:event_date)
			#@events = Event.where("email = :email AND deleted = :deleted AND title LIKE :pattern",{ email: "#{current_user.email}", deleted: false, pattern: "%#{params[:search_this]}%" })

			if !@events.empty?
				@current_day = @events[0].event_date
			end
		end
		@search_term = params[:search_this]
		@to_display  = "S"
		render "index"
	end


	def show_private
		@events = Event.where(email: current_user.email, deleted: false, is_private: true).order(:event_date)

		if !@events.empty?
			@current_day = @events[0].event_date
		end
		@to_display  = "P"
		render "index"
	end


	def show_deleted
		#this returns private and public events
		@events = Event.where(email: current_user.email, deleted: true).order(:event_date)

		if !@events.empty?
			@current_day = @events[0].event_date
		end
		@to_display  = "D"
		render "index"
	end



	def restore
		@event = Event.find(params[:id])

		@event.deleted = false

		if @event.save
			redirect_to show_deleted_events_path #go to deleted events
		else
			redirect_to event_path #display event
			#I should display error message as well
		end	
	end



#Private section

private

	#Make sure the 'event' key is in the params hash: _require_ method

	#add stuff to the white list: _permit_ method
	def safe_params
		params.require(:event).permit(:title, :event_date, :begti, :endti, :comments, :has_length, :is_private)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<!-- Error section -->
<% if @event.errors.any? %>
<div class="col-sm-6 col-sm-offset-2 alert alert-danger">
	<%= pluralize(@event.errors.count, "error") %> while creating event
	<ul>
		<% @event.errors.full_messages.each do |message| %>
			<!-- use gsub? -->
			<% if message.include? "Begti" %>
				<% message["Begti"] = "Begin time" %>
			<% end %>
			<% if message.include? "Endti" %>
				<% message["Endti"] = "End time" %>
			<% end %>		
			<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>


<div class="container-fluid">
	<div class="row">

		<div class="col-sm-6 col-sm-offset-2 table_header">
			<h2>Edit "<%= @event.title %>"</h2>
		</div>


		<div class="col-sm-6 col-sm-offset-2 calendar greybox">
			<%= form_for @event do |f| %>
				<p>
					<%= f.label :title %>
					<%= f.text_field :title, size: 40, maxlength: 40 %>
				</p>

				<p>
					<%= f.label :event_date, "Date" %>
					<%= f.date_field(:event_date) %>
				</p>

				<p>
					<%= f.label :has_length %>
					<%= f.check_box(:has_length) %>
				</p>


				<p>
					<label for="event_begti" id="time_label">From</label>
					<%= f.time_field(:begti) %>


					<span id="hidden_to_field">
						<%= f.label :endti, "to" %>
						<%= f.time_field(:endti) %>
					</span>
				</p>

				<p>
					<%= f.label :is_private, "Private event" %>
					<%= f.check_box(:is_private) %>
				</p>

				<p>
					<%= f.label :comments %><br/>
					<%= f.text_area :comments %>
				</p>

				<br/>
				<%= f.submit "Update", class: "btn btn-default" %>
				<%= f.submit "Cancel", class: "btn btn-default" %>

			<% end %> <!-- end of form -->

		</div>
	</div>
</div>

app/views/events/index.html.erb
<div class="container-fluid">
	<div class="row">
		<% case @to_display %>
		<% when "I" #index %>

		<div class="col-sm-4 col-sm-offset-2">
			<h2>My planning</h2>

			<!-- 'Add' button to create a new event -->
			<form class="navbar-form" action="/events/new">
				<button type="submit" class="btn btn-default">Add</button>
			</form>			
		</div>

	</div>
	<% when "S" #search %>

	<div class="col-sm-6 col-sm-offset-2">
		<!-- <h2><%= pluralize(@events.length, "event") %> containing "<%= "#{params[:search_this]}" %>"</h2> -->

		<h2 class="search" data-search-term="<%= @search_term %>"><%= pluralize(@events.length, "event") %> containing "<%= @search_term %>"</h2>
	</div>

</div>
<% when "P" #private %>

<div class="col-sm-4 col-sm-offset-2">
	<h2>My private events</h2>			
</div>

</div>
<% when "D" #deleted %>

<div class="col-sm-4 col-sm-offset-2">
	<h2>Deleted events</h2>			
</div>

</div>			
<% end #end case %>


<!-- Now we populate the table that contains all the events -->
<!-- This receives the table with the events ORDERED BY DATE -->
<div class="row">

	<div class="col-sm-4 col-sm-offset-2 greybox">

		<% if !@events.empty? %>
		<!-- <% current_day = @events[0].event_date %> -->

		<table class="table table-condensed table-bordered">

			<tr>
				<th class="table_header">
					<%= @current_day.strftime('%a %-d %b %Y') %>
				</th>
			</tr>

			<% @events.each do |event| %>

			<% if event.event_date == @current_day %>

			<!-- Create an open (true=do not close tag) tr tag -->
			<%= tag("tr", {class: "clickable_row",
				data: { url: "/events/#{event[:id]}" }}, true) %>


					<td>
					
					<span class="search_title"><span class="search"><%= event.title %></span></span><br/>

						<%= event.begti.strftime("%I:%M %P") %>
						<% if event.has_length %>
						-<%= event.endti.strftime("%I:%M %P") %>
						<% end %><br/>
					</td>

				</tr>

				<% else %>
			</table>
			<!-- <hr/> -->
			<table class="table table-condensed table-bordered">
				<% @current_day = event.event_date %>
				<tr>
					<th class="table_header">
						<%= @current_day.strftime('%a %-d %b %Y') %>
					</th>
				</tr>
				<%= tag("tr", {class: "clickable_row",
					data: { url: "/events/#{event[:id]}" }}, true) %>

				<td>

					<span class="search_title">
						<span class="search"><%= event.title %></span>
					</span><br/>
						<%= event.begti.strftime("%I:%M %P") %>

						<% if event.has_length %>
						-<%= event.endti.strftime("%I:%M %P") %>
						<% end %>
						<br/>
					</td>
				</tr>
				<% end #if/else block %>

				<% end #loop end %>

			</table>

			<% else #table is empty %>

			<table class="table table-condensed table-bordered">
				<tr><td>No events to show</td></tr>
			</table>

			<% end #if %>

		</div>

	</div>

</div>

app/views/events/new.html.erb
<!-- Error section -->
<% if @event.errors.any? %>
	<div class="col-sm-6 col-sm-offset-2 alert alert-danger">
		<%= pluralize(@event.errors.count, "error") %> while creating event
		<ul>
			<% @event.errors.full_messages.each do |message| %>
				<!-- use gsub? -->
				<% if message.include? "Begti" %>
					<% message["Begti"] = "Begin time" %>
				<% end %>
				<% if message.include? "Endti" %>
					<% message["Endti"] = "End time" %>
				<% end %>				
				<li><%= message %></li>
			<% end %>			
		</ul>
	</div>
<% end %>


<div class="container-fluid">
	<div class="row">

		<div class="col-sm-6 col-sm-offset-2 table_header">
			<h2>New event</h2>
		</div>

		<div class="col-sm-6 col-sm-offset-2 calendar greybox">

			<%= form_for @event do |f| %>
				<p>
					<%= f.label :title %>
					<%= f.text_field :title, size: 40, maxlength: 40 %>
				</p>

				<p>
					<%= f.label :event_date, "Date" %>
					<%= f.date_field(:event_date) %>
				</p>

				<p>
					<%= f.label :has_length %>
					<%= f.check_box :has_length %>
				</p>

				<p>
					<label for="event_begti" id="time_label">From</label>
					<%= f.time_field(:begti) %>

					<span id="hidden_to_field">
						<%= f.label :endti, "to" %>
						<%= f.time_field(:endti) %>
					</span>

				</p>

				<p>
					<%= f.label :is_private, "Private event" %>
					<%= f.check_box :is_private %>
				</p>

				<p>
				<%= f.label     :comments %><br/>
				<%= f.text_area :comments %>
				</p>

				<br/>
				<%= f.submit "Create", class: "btn btn-default" %>
				<%= f.submit "Cancel", class: "btn btn-default" %>

			<% end %>

		</div>
	</div>
</div>

app/views/events/show.html.erb
<div class="container-fluid">
	<div class="row">

		<div class="col-sm-6 col-sm-offset-2 table_header">
			<h2><%= @event.title %></h2>
		</div>

		<div class="col-sm-6 col-sm-offset-2 calendar greybox">

			<div class="dropdown next_to">

				<button data-toggle="dropdown" class="btn btn-default dropdown-toggle">Action<span class="caret"></span>
				</button>

				<ul class="dropdown-menu">
					<% if @event.deleted %>
						<!-- Show the restore option -->
						<li><%= link_to "Restore", restore_path %></li>
					<% else %>
						<!-- Do not show the delete option if event is already deleted -->
						<li><%= link_to "Delete", event_path, method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %></li>
						<!-- nor the 'edit' option -->
						<li><%= link_to "Edit", edit_event_path %></li>
					<% end %>
				</ul>

			</div>

			<table class="borderless">

				<tr>
					<td><%= @event.event_date.strftime('%a %-d %b %Y') %></td>
				</tr>

				<tr>
					<td>
						<!-- Show only begin time if it has no length -->
						<% if @event.has_length %>
							From <%= @event.begti.strftime("%I:%M %P") %>
							to <%= @event.endti.strftime("%I:%M %P") %>
						<% else %>
							At <%= @event.begti.strftime("%I:%M %P") %>
						<% end %>
					</td>
				</tr>

				<tr>
					<td>
						<br/>Private event
						<%= check_box_tag "event_is_private", nil, checked=@event.is_private, disabled: true %>
					</td>
				</tr>

				<tr>
					<td>
						<br/>Comments
					</td>
				</tr>
		
				<tr>
					<td>
						<textarea size="40" maxlength="40" disabled><%= @event.comments %></textarea>
					</td>
				</tr>

				<tr>
					<td>
						<form method="get" action=<%= events_path %>>
							<button class="btn btn-default" value="Back">
								<span class="glyphicon glyphicon-chevron-left"></span>
							</button>
						</form>
					</td>

					<td><a href="https://www.google.com/calendar/render?action=TEMPLATE&text=<%= @event.title %>&dates=<%= @complete_date %>&details=<%= @event.comments %>&sf=true&output=xml" target="_blank">
						<%= image_tag "gc_button3.gif" %>
					</a></td>
				</tr>
			</table>

		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Plannie</title>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>

 <!-- Google font -->
 <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>  
</head>
<body>


  <!-- Display menu only if the user is logged: -->
  <% if !current_user.nil? %>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- hamburger button for mobile -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Plannie", events_path, class: "navbar-brand glyphicon glyphicon-calendar" %>
      </div>


      <!-- Menu bar -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!-- Search -->
        <ul class="nav navbar-nav">
          <li>
            <form class="navbar-form" action="/events/search">
              <input type="text" name="search_this" class="form-control" placeholder="Search event...">
              <button type="submit" value="search" class="btn btn-default glyphicon glyphicon-search">Search</button>
            </form>
          </li>

          <!-- Dropdown menu -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <!-- <li><a href="#">My profile</a></li> -->

              <li><a id="popup" href=<%= events_path %> ><span class="glyphicon glyphicon-home menu_icon">
              </span>Home</a>
              </li>              
              
              <li><a id="popup" href=<%= show_private_events_path %> ><span class="glyphicon glyphicon-lock menu_icon">
              </span>Private events</a>
              </li>

              <li><a href=<%= show_deleted_events_path %>><span class="glyphicon glyphicon-trash menu_icon"></span>Deleted events</a></li>


              <li class="divider"></li>

              <li><a href=<%= destroy_user_session_path %> data-method="delete"><span class="glyphicon glyphicon-off menu_icon"></span>Sign out</a></li>

            </ul>
          </li>

        </ul>

      </div><!-- navbar-collapse -->
    </div><!-- container-fluid -->
  </nav>

  <% end %>

  <%= yield %>

</body>
</html>

app/views/plannie_notifier/last_sign_in.text.erb
PlannieNotifier#last_sign_in

<%= @greeting %>, find me in app/views/app/views/plannie_notifier/last_sign_in.text.erb


#Dear <%= @current_user.name %>
#Thank you for your recent order from The Pragmatic Store.
#You ordered the following items:
#<%= render @order.line_items -%>
#We'll send you a separate e-mail when your order ships.

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>